runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
#  static_dir: /static
  upload: /dist/index.html

- url: /static
  static_dir: /dist/static

#service: default